spring.application.name=banking-app-apis
spring.datasource.url=jdbc:mysql://localhost:3306/banking_app
spring.datasource.username=root
spring.datasource.password=Admin@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=9a5b6d7b70bedf
spring.mail.password=0c99ad37a449b7
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.jwt-secret=xezMOvg4EluJUB9ztYt5PDqqCqYixjAZgR5UiIaMg2I=
app.jwt-expiration=864000